name: Deploy on GitHub Pages

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  cache-and-install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install packages
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.x.x
          run_install: |
            - args: [--frozen-lockfile]

      - name: Build
        run: pnpm build

      - name: Deploy on GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: ./dist